url: https://indybushido.github.io
baseurl:

# Site settings
title: Indy Bushido
email: indybushido@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- position: 1
  name: Sensei John Hoffmire
  pic: John
  position: Hachidan
  description:
    - Began training in Isshinryu Karate in 1971
    - 8th Dan Isshinryu Karate
    - IWKA Certified Isshinryu Instructor
    - Co-owner Isshinryu Bushido LLC
    - Retired Indianapolis Firefighter

- position: 2
  name: Sensei Larry Tylenda
  pic: Larry
  position: Godan
  description:
    - Began training at Isshinryu Bushido in 1999
    - Certified Isshinryu Karate instructor
    - Co-owner Isshinryu Bushido LLC

- position: 3
  name: Sensei Shellee Tylenda
  pic: Shellee
  position: Yondan
  description:
    - Began training at Isshinryu Bushido in 2001
    - Certified Isshinryu Karate instructor
    - Co-owner Isshinryu Bushido LLC

- position: 4
  name: Sensei Maddie Kerr
  pic: Maddie
  position: Yondan
  description:
    - Began training at Isshinryu Bushido in 1998

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty